version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: project_final
    networks:
      - your-custom-network
    container_name: mysql
    aliases:
      - mysql

  spring-boot-container:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    networks:
      - your-custom-network
    command: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "springBoot-0.0.1-SNAPSHOT.jar"]
    environment:
      DOCKER_USERNAME: "${DOCKER_USERNAME}"
      DOCKER_PASSWORD: "${DOCKER_PASSWORD}"

networks:
  your-custom-network:
    driver: bridge
