# name: Build and Deploy Docker Image

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up JDK 8
#         uses: actions/setup-java@v2
#         with:
#           distribution: 'adopt'
#           java-version: '8'

#       - name: Build with Maven
#         run: mvn -B clean install

#       - name: Log in to Docker Hub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#       - name: Build Docker image
#         run: docker-compose -f docker-compose.yml build

#       - name: Push Docker image to Docker Hub
#         run: docker-compose -f docker-compose.yml push

#       - name: Deploy with Docker Compose
#         run: docker-compose -f docker-compose.yml up -d

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     if: github.event_name == 'push' && github.ref == 'refs/heads/master'

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Log in to Docker Hub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

